apiVersion: v1
kind: ServiceAccount
metadata:
  name: revision-controller
  namespace: knative-serving

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: revision-controller
rules:
  - apiGroups:
      - ""
    resources:
      - 'configmaps'
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - serving.knative.dev
    resources:
      - '*'
    verbs:
      - get
      - list
      - create
      - watch
      - patch
      - delete
      - update

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: revision-controller-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: revision-controller
subjects:
  - kind: ServiceAccount
    name: revision-controller
    namespace: knative-serving
